name: Deploy web app to Azure Static Web Apps

on:
  push:
    branches: [ "main" ]

env:
  APP_LOCATION: "client"         # pasta onde está seu front (com package.json)
  API_LOCATION: ""               # deixe vazio se não tiver backend/API
  APP_ARTIFACT_LOCATION: "dist"  # pasta onde o build gera os arquivos estáticos

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: client     # importante: instalar dentro da pasta client

      - name: Build app
        run: npm run build
        working-directory: client     # importante: build dentro da pasta client

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_FLOWER_08CD45E1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
